#!/usr/bin/env node
'use strict';
// Writes `src/version.generated.ts`, a single `LIBRARY_VERSION` constant
// copied from `package.json`'s own `version` field. `src/version.ts` imports
// it instead of doing a runtime `require('../package.json')` (plan.md phase 3
// "src/version.ts": a bundler that prunes non-JS files - or one that can't
// resolve a `require()` reaching outside `lib/` at all - breaks that; see
// PR #16's review).
//
// Run as `prebuild` (so `lib/version.js` always ships the version being
// built, including right after `changeset version` bumps `package.json`) and
// as `pretest:jest`/`pretypecheck` (so ts-jest and `tsc -p tsconfig.json`,
// which compile `src/` directly rather than `lib/`, see a file that matches
// `package.json` too). The generated file is not committed (see
// `.gitignore`); every one of those entry points regenerates it first.
const fs = require('node:fs');
const path = require('node:path');

const packageJsonPath = path.join(__dirname, '..', 'package.json');
const { version } = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));

const outPath = path.join(__dirname, '..', 'src', 'version.generated.ts');
const banner = '// Generated by scripts/generate-version.js - do not edit.\n';
const contents = `${banner}export const LIBRARY_VERSION: string = ${JSON.stringify(
  version ?? '0.0.0',
)};\n`;

fs.writeFileSync(outPath, contents);
